using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using WindowsFormsApp4.Entity;

namespace WindowsFormsApp4.Formlar
{
    public partial class FrmDepartmanlar : Form
    {
        public FrmDepartmanlar()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }
        dbis_TakipEntities6 db = new dbis_TakipEntities6();
        void Listele()
        {
            
            var degerler = (from x in db.tbldepartmanlar
                            select new
                            {
                                x.ID,
                                x.Ad
                            }).ToList();
            gridControl1.DataSource = degerler;
        }
        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void BtnListele_Click(object sender, EventArgs e)
        {
            Listele();
        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {

        }

        private void BtnEkle_Click(object sender, EventArgs e)
        {
            tbldepartmanlar t= new tbldepartmanlar();
            t.Ad =TxtAd.Text;
            db.tbldepartmanlar.Add(t);
            db.SaveChanges();
            XtraMessageBox.Show("Departman başarılı bir şekilde sisteme kaydedildi", "Bilgi", MessageBoxButtons.OK,MessageBoxIcon.Information);
            Listele();
        }

        private void BtnSil_Click(object sender, EventArgs e)
        {
            int x = int.Parse(TxtID.Text);
            var deger = db.tbldepartmanlar.Find(x);
            db.tbldepartmanlar.Remove(deger);
            db.SaveChanges();
            XtraMessageBox.Show("Departman silme işlemi başarılı bir şekilde gerçekleşti.", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Stop);
            Listele();
        }

        private void gridView1_FocusedRowChanged(object sender,
            DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            var idDegeri = gridView1.GetFocusedRowCellValue("ID");
            var adDegeri = gridView1.GetFocusedRowCellValue("Ad");

            // Değer null değilse ToString() yapalım
            if (idDegeri != null)
            {
                TxtID.Text = idDegeri.ToString();
            }
            else
            {
                TxtID.Text = ""; // Null ise kutuyu boşalt
            }

            if (adDegeri != null)
            {
                TxtAd.Text = adDegeri.ToString();
            }
            else
            {
                TxtAd.Text = ""; // Null ise kutuyu boşalt
            }

        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            int x = int.Parse(TxtID.Text);
            var deger = db.tbldepartmanlar.Find(x);
            deger.Ad = TxtAd.Text;
            db.SaveChanges();
            XtraMessageBox.Show("Departman güncelleme işlemi başarılı bir şekilde gerçekleşti.", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
            Listele();
        }

        private void FrmDepartmanlar_Load(object sender, EventArgs e)
        {

        }
    }
}
